### ISSUE TITLE
Charts and Filters for Officers Shot data

### ISSUE THREAD

**Issue by ifsimicoded** [texas-justice-initiative/website#116]
Data columns:
year, officer_age, officer_race, officer_gender
civilian_age_1, civilian_race_1, civilian_gender_1, civilian_died, agency_name, 
if you go with age -- I'll need to work with @wetchler to update the data to have age groups.

- [ ] filters
- [ ] charts
- [ ] data summary/description

@EvaRuthM will you provide specifics for the above.

**Comment by ifsimicoded** [comment]
Sample charts for PR:
![officers_shot_data](https://user-images.githubusercontent.com/3039125/47983330-ce3b4e00-e087-11e8-98dc-ef36346e0793.gif)

**Comment by EvaRuthM** [comment]
- [ ] filters 
  - Year 
  - Officer Race _(Google Doc column heading is 'Injured or Deceased's Race/Ethnicity')_
  - Officer Died _(true or false - under heading 'Incident Resulted in 1')_
  - Civilian Shot _(killed, injured or no - under heading 'Incident Resulted in 2')_ 
  - agency name 
  - agency county 
- [ ] charts 
  - Year 
  - Officer Race _(under 'Injured or Deceased's race')_
  - Officer Gender _(under 'Injured or Deceased's Gender')_
  - Officer Shot _(choices of 'injured,' and 'killed' – under 'Incident Resulted in 1')_
  - Civilian Race _(under 'Non-Officer Race/Ethnicity 1')_
  - Civilian Gender _(under 'Non-Peace Officer's Age 1')_
  - Civilian Shot _(choices of 'injured', 'killed,' and 'not shot' – under 'Incident Resulted in 2')_
- [ ] data summary/description 
  - Shootings that injured or killed Texas law enforcement officers since Sept. 2015, as reported to the Office of the Attorney General.

**Comment by EvaRuthM** [comment]
assigning @LayaTaal to work on plug-in on staging to address the boxes instead of carrots

**Comment by ifsimicoded** [comment]
Closing and logging carrot/font-awesome bug in separate issue. Closed by PR #117 and #118
