### ISSUE TITLE
post-automation tasks

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#126]
Upon completion of #59, #25: 

- [x] @aidenyang: pull slider numbers from new data file; to include: 
  - total number of custodial deaths since 2005 (first slide) 
  - total number of civilians shot by law enforcement since 2015 (second slide) 
  - total number of officers shot by civilians since 2015 (third slide) 
- [ ] @judan @LayaTaal: update where chart data comes from

**Comment by aidenyang** [comment]
@judan @LayaTaal @ifsimicoded re: the slider numbers, I think this would be a change on the frontend. I looked into how the slider numbers are currently pulled, and it looks like it's using the compressed json already; nothing needs to change except for using the compressed json from s3 instead of on the server.

**Comment by aidenyang** [comment]
@judan Let's chat tomorrow f2f about this, but I can work with you to pull the data from s3. We can just sit down and do it together or I can write something up for you; whichever works best.
