### ISSUE TITLE
"no data" when no relevant data available

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/website#168]
On "explore," when you type in a county that has no cases (i.e. look at "OIS - officers shot by civilian" data and type in "williamson"), the graphs default to showing all cases. 
  - CHANGE so that the graphs disappear and "No Data" comes up instead

**Comment by sheadscott** [comment]
@judan @LayaTaal I created a new branch `ss-data-filter-input-validation` for this issue and added some pseudocode. After looking at the dev environment setup, I wasn't sure it would be worth all the effort since we will be moving away from Wordpress soon. I'm more than happy to set it up if there are compelling reasons, but it seems like my time might be better spent working on the React site.

What do y'all think?

**Comment by LayaTaal** [comment]
@sheadscott @judan I'm ok putting this on hold so we can focus on the site redesign. We can implement this along with the new version.
